-- Canal do operario: modelo compartilhado pelo WhatsApp agora e pelo app no futuro.
create table public.canais_operario (
  id bigint generated by default as identity primary key,
  obra_id integer not null references public.obras(id) on delete cascade,
  colaborador_id integer not null references public.colaboradores(id) on delete cascade,
  tipo text not null default 'whatsapp' check (tipo in ('whatsapp', 'flutter')),
  telefone_e164 text not null check (telefone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  status text not null default 'pendente' check (status in ('pendente', 'ativo', 'bloqueado', 'inativo')),
  codigo_ativacao_hash text,
  codigo_expira_em timestamptz,
  tentativas_ativacao smallint not null default 0 check (tentativas_ativacao between 0 and 5),
  ativado_em timestamptz,
  ultimo_contato_em timestamptz,
  criado_por uuid not null references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (colaborador_id, tipo)
);

create index canais_operario_obra_idx on public.canais_operario(obra_id);
create unique index canais_operario_whatsapp_telefone_idx
  on public.canais_operario(telefone_e164)
  where tipo = 'whatsapp' and status <> 'inativo';

create table public.sessoes_operario (
  canal_id bigint primary key references public.canais_operario(id) on delete cascade,
  tarefa_ativa_id integer references public.tarefas(id) on delete set null,
  estado text not null default 'menu',
  dados jsonb not null default '{}'::jsonb,
  atualizado_em timestamptz not null default now()
);

create table public.whatsapp_outbox (
  id bigint generated by default as identity primary key,
  canal_id bigint not null references public.canais_operario(id) on delete cascade,
  telefone_e164 text not null,
  tipo text not null default 'texto' check (tipo in ('texto', 'imagem')),
  corpo text not null,
  metadados jsonb not null default '{}'::jsonb,
  status text not null default 'pendente' check (status in ('pendente', 'processando', 'enviado', 'erro')),
  tentativas smallint not null default 0 check (tentativas >= 0),
  disponivel_em timestamptz not null default now(),
  processando_em timestamptz,
  enviado_em timestamptz,
  provider_id text,
  ultimo_erro text,
  criado_em timestamptz not null default now()
);

create index whatsapp_outbox_pendente_idx
  on public.whatsapp_outbox(disponivel_em, id)
  where status in ('pendente', 'processando');

create table public.whatsapp_inbox (
  provider_id text primary key,
  canal_id bigint references public.canais_operario(id) on delete set null,
  telefone_e164 text not null,
  tipo text not null,
  corpo text,
  possui_midia boolean not null default false,
  metadados jsonb not null default '{}'::jsonb,
  status text not null default 'recebido' check (status in ('recebido', 'processado', 'ignorado', 'erro')),
  erro text,
  recebido_em timestamptz not null default now(),
  processado_em timestamptz
);

create table public.evidencias_tarefa (
  id bigint generated by default as identity primary key,
  tarefa_id integer not null references public.tarefas(id) on delete cascade,
  colaborador_id integer not null references public.colaboradores(id),
  canal_id bigint references public.canais_operario(id) on delete set null,
  inbox_provider_id text unique references public.whatsapp_inbox(provider_id),
  tipo text not null default 'foto' check (tipo in ('foto', 'documento')),
  storage_path text not null unique,
  mime_type text not null,
  legenda text,
  criado_em timestamptz not null default now()
);

create index evidencias_tarefa_tarefa_idx on public.evidencias_tarefa(tarefa_id, criado_em);

alter table public.canais_operario enable row level security;
alter table public.sessoes_operario enable row level security;
alter table public.whatsapp_outbox enable row level security;
alter table public.whatsapp_inbox enable row level security;
alter table public.evidencias_tarefa enable row level security;

revoke all on public.canais_operario, public.sessoes_operario,
  public.whatsapp_outbox, public.whatsapp_inbox, public.evidencias_tarefa
  from anon, authenticated;
grant select on public.canais_operario, public.evidencias_tarefa to authenticated;

create policy gestor_select on public.canais_operario for select to authenticated
using (private.possui_obra(obra_id));

create policy gestor_select on public.evidencias_tarefa for select to authenticated
using (
  exists (
    select 1 from public.tarefas t
    where t.id = tarefa_id and private.possui_obra(t.obra_id)
  )
);

-- Fotos ficam privadas; gestores recebem URLs assinadas pelo cliente autenticado.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'evidencias-tarefa',
  'evidencias-tarefa',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy gestor_le_evidencia on storage.objects for select to authenticated
using (
  bucket_id = 'evidencias-tarefa'
  and private.possui_obra(
    case
      when (storage.foldername(name))[1] ~ '^[0-9]+$'
      then ((storage.foldername(name))[1])::integer
      else null
    end
  )
);

-- O historico passa a aceitar producao avulsa e solicitacao de conclusao.
alter table public.evolucoes_tarefa drop constraint evolucoes_tarefa_tipo_check;
alter table public.evolucoes_tarefa add constraint evolucoes_tarefa_tipo_check check (
  tipo in (
    'inicio', 'pausa', 'retomada', 'conclusao', 'impedimento',
    'producao', 'solicitacao_conclusao'
  )
);
alter table public.tarefas drop constraint tarefas_status_check;
alter table public.tarefas add constraint tarefas_status_check check (
  status in ('nao_iniciada', 'em_execucao', 'pausada', 'concluida', 'bloqueada', 'aguardando_validacao')
);

create or replace function private.registrar_evolucao(
  p_tarefa integer,
  p_tipo text,
  p_quantidade numeric,
  p_motivo text,
  p_observacao text
) returns integer
language plpgsql security definer set search_path = '' as $$
declare tarefa public.tarefas; novo_status text; evento integer;
begin
 select t.* into tarefa
 from public.tarefas t
 join public.obras o on o.id=t.obra_id
 where t.id=p_tarefa and o.dono_id=auth.uid() and o.ativo
 for update of t;
 if not found then raise exception 'Tarefa nao encontrada.'; end if;
 if p_quantidade is null or p_quantidade<0 then raise exception 'Quantidade invalida.'; end if;
 if p_tipo='inicio' and tarefa.status='nao_iniciada' then novo_status:='em_execucao';
 elsif p_tipo='pausa' and tarefa.status='em_execucao' then novo_status:='pausada';
 elsif p_tipo='retomada' and tarefa.status in ('pausada','bloqueada','aguardando_validacao') then novo_status:='em_execucao';
 elsif p_tipo='conclusao' and tarefa.status in ('em_execucao','aguardando_validacao') then novo_status:='concluida';
 elsif p_tipo='impedimento' and tarefa.status in ('nao_iniciada','em_execucao','pausada') then novo_status:='bloqueada';
 elsif p_tipo='producao' and tarefa.status='em_execucao' then novo_status:=tarefa.status;
 else raise exception 'Esta acao nao e permitida no estado atual da tarefa.'; end if;
 if p_tipo='impedimento' and (p_motivo is null or p_motivo not in ('falta_material','falta_ferramenta','frente_ocupada','projeto_pendente','chuva','espera_equipe','seguranca','outro')) then raise exception 'Informe o motivo do impedimento.'; end if;
 if p_tipo in ('inicio','retomada') and p_quantidade<>0 then raise exception 'Registre producao ao pausar, concluir ou informar impedimento.'; end if;
 if p_tipo='producao' and p_quantidade<=0 then raise exception 'Informe uma quantidade maior que zero.'; end if;
 insert into public.evolucoes_tarefa(tarefa_id,autor_id,tipo,quantidade_realizada,motivo_impedimento,observacao)
 values(p_tarefa,auth.uid(),p_tipo,p_quantidade,case when p_tipo='impedimento' then p_motivo else null end,p_observacao)
 returning id into evento;
 update public.tarefas set status=novo_status,atualizado_em=now() where id=p_tarefa;
 return evento;
end $$;

create or replace function private.normalizar_telefone(p_telefone text) returns text
language plpgsql immutable security invoker set search_path = '' as $$
declare digitos text := regexp_replace(coalesce(p_telefone,''), '[^0-9]', '', 'g');
begin
  if length(digitos) in (10,11) then digitos := '55' || digitos; end if;
  if length(digitos) < 10 or length(digitos) > 15 then
    raise exception 'Telefone invalido. Informe DDD e numero.';
  end if;
  return '+' || digitos;
end $$;

create function private.tarefa_atribuida(p_canal bigint, p_tarefa integer) returns boolean
language sql stable security invoker set search_path = '' as $$
  select exists (
    select 1
    from public.canais_operario c
    join public.tarefas t on t.id = p_tarefa and t.obra_id = c.obra_id
    where c.id = p_canal and c.status = 'ativo' and c.tipo = 'whatsapp'
      and (
        t.colaborador_id = c.colaborador_id
        or exists (
          select 1 from public.equipe_colaboradores ec
          where ec.equipe_id = t.equipe_id
            and ec.colaborador_id = c.colaborador_id
            and ec.ativo
            and t.data >= ec.data_inicio
            and (ec.data_fim is null or t.data <= ec.data_fim)
        )
      )
  );
$$;

create function public.emitir_acesso_operario(p_colaborador integer)
returns table(canal_id bigint, codigo text, telefone_e164 text, expira_em timestamptz)
language plpgsql security definer set search_path = '' as $$
declare c public.colaboradores; v_codigo text; v_canal bigint; v_telefone text; v_expira timestamptz;
begin
  select col.* into c
  from public.colaboradores col
  join public.obras o on o.id=col.obra_id
  where col.id=p_colaborador and col.ativo and o.ativo and o.dono_id=auth.uid();
  if not found then raise exception 'Colaborador nao encontrado.'; end if;
  v_telefone := private.normalizar_telefone(c.telefone);
  v_codigo := lpad((floor(random()*1000000))::integer::text, 6, '0');
  v_expira := now() + interval '24 hours';

  insert into public.canais_operario(
    obra_id,colaborador_id,tipo,telefone_e164,status,codigo_ativacao_hash,
    codigo_expira_em,tentativas_ativacao,ativado_em,criado_por,atualizado_em
  ) values (
    c.obra_id,c.id,'whatsapp',v_telefone,'pendente',
    encode(extensions.digest(v_codigo,'sha256'),'hex'),v_expira,0,null,auth.uid(),now()
  )
  on conflict (colaborador_id,tipo) do update set
    telefone_e164=excluded.telefone_e164,status='pendente',
    codigo_ativacao_hash=excluded.codigo_ativacao_hash,codigo_expira_em=excluded.codigo_expira_em,
    tentativas_ativacao=0,ativado_em=null,criado_por=auth.uid(),atualizado_em=now()
  returning id into v_canal;

  insert into public.sessoes_operario(canal_id) values(v_canal)
  on conflict (canal_id) do update set tarefa_ativa_id=null,estado='menu',dados='{}',atualizado_em=now();

  insert into public.whatsapp_outbox(canal_id,telefone_e164,corpo)
  values(
    v_canal,v_telefone,
    format('Ola, %s! Voce recebeu acesso ao acompanhamento da obra. Responda *ATIVAR %s* em ate 24 horas. Se nao reconhece esta mensagem, ignore.', c.nome, v_codigo)
  );
  return query select v_canal,v_codigo,v_telefone,v_expira;
end $$;

revoke all on function public.emitir_acesso_operario(integer) from public,anon;
grant execute on function public.emitir_acesso_operario(integer) to authenticated;

create function public.desativar_acesso_operario(p_canal bigint) returns void
language plpgsql security definer set search_path = '' as $$
begin
  update public.canais_operario c set status='inativo',codigo_ativacao_hash=null,
    codigo_expira_em=null,atualizado_em=now()
  where c.id=p_canal and private.possui_obra(c.obra_id);
  if not found then raise exception 'Canal nao encontrado.'; end if;
end $$;
revoke all on function public.desativar_acesso_operario(bigint) from public,anon;
grant execute on function public.desativar_acesso_operario(bigint) to authenticated;

create function public.registrar_whatsapp_inbox(
  p_provider_id text,p_telefone text,p_tipo text,p_corpo text,
  p_possui_midia boolean default false,p_metadados jsonb default '{}'::jsonb
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_phone text; v_canal public.canais_operario; inseriu integer;
begin
  v_phone := private.normalizar_telefone(p_telefone);
  select * into v_canal from public.canais_operario
  where tipo='whatsapp' and telefone_e164=v_phone and status<>'inativo'
  order by id desc limit 1;
  insert into public.whatsapp_inbox(provider_id,canal_id,telefone_e164,tipo,corpo,possui_midia,metadados)
  values(p_provider_id,v_canal.id,v_phone,p_tipo,p_corpo,p_possui_midia,coalesce(p_metadados,'{}'::jsonb))
  on conflict (provider_id) do nothing;
  get diagnostics inseriu = row_count;
  if inseriu=0 then return jsonb_build_object('aceita',false); end if;
  if v_canal.id is not null then
    update public.canais_operario set ultimo_contato_em=now(),atualizado_em=now() where id=v_canal.id;
  end if;
  return jsonb_build_object('aceita',true,'canal_id',v_canal.id,'status',v_canal.status);
end $$;

create function public.ativar_canal_whatsapp(p_telefone text,p_codigo text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_phone text; c public.canais_operario;
begin
  v_phone := private.normalizar_telefone(p_telefone);
  select * into c from public.canais_operario
  where tipo='whatsapp' and telefone_e164=v_phone and status='pendente'
  order by id desc limit 1 for update;
  if not found then raise exception 'Nenhum acesso pendente para este telefone.'; end if;
  if c.codigo_expira_em < now() then
    return jsonb_build_object('ativado',false,'erro','Codigo expirado. Solicite um novo acesso ao gestor.');
  end if;
  if c.tentativas_ativacao >= 5 then
    return jsonb_build_object('ativado',false,'erro','Acesso bloqueado. Solicite um novo codigo ao gestor.');
  end if;
  if c.codigo_ativacao_hash <> encode(extensions.digest(trim(p_codigo),'sha256'),'hex') then
    update public.canais_operario set tentativas_ativacao=tentativas_ativacao+1,
      status=case when tentativas_ativacao+1>=5 then 'bloqueado' else status end,
      atualizado_em=now() where id=c.id;
    return jsonb_build_object('ativado',false,'erro','Codigo invalido.');
  end if;
  update public.canais_operario set status='ativo',codigo_ativacao_hash=null,
    codigo_expira_em=null,tentativas_ativacao=0,ativado_em=now(),atualizado_em=now()
  where id=c.id;
  insert into public.sessoes_operario(canal_id) values(c.id) on conflict do nothing;
  return jsonb_build_object('ativado',true,'canal_id',c.id,'colaborador_id',c.colaborador_id,'obra_id',c.obra_id);
end $$;

create function public.listar_tarefas_whatsapp(p_canal bigint) returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.data,x.id),'[]'::jsonb)
  from (
    select t.id,t.data,t.turno,t.quantidade_meta,t.unidade,t.status,
      s.nome servico,f.nome frente
    from public.tarefas t
    join public.servicos s on s.id=t.servico_id
    join public.frentes f on f.id=t.frente_id
    where private.tarefa_atribuida(p_canal,t.id)
      and t.status <> 'concluida'
      and t.data between current_date-interval '7 days' and current_date+interval '14 days'
  ) x;
$$;

create function public.registrar_evolucao_operario(
  p_canal bigint,p_tarefa integer,p_tipo text,p_quantidade numeric default 0,
  p_motivo text default null,p_observacao text default null
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare c public.canais_operario; t public.tarefas; v_tipo text; v_status text; v_evento integer;
begin
  if not private.tarefa_atribuida(p_canal,p_tarefa) then raise exception 'Tarefa nao atribuida a este colaborador.'; end if;
  select * into c from public.canais_operario where id=p_canal and status='ativo';
  select * into t from public.tarefas where id=p_tarefa for update;
  if p_quantidade is null or p_quantidade<0 then raise exception 'Quantidade invalida.'; end if;
  if p_tipo='inicio' and t.status='nao_iniciada' then v_tipo:='inicio'; v_status:='em_execucao';
  elsif p_tipo='pausa' and t.status='em_execucao' then v_tipo:='pausa'; v_status:='pausada';
  elsif p_tipo='retomada' and t.status in ('pausada','bloqueada') then v_tipo:='retomada'; v_status:='em_execucao';
  elsif p_tipo='producao' and t.status='em_execucao' and p_quantidade>0 then v_tipo:='producao'; v_status:=t.status;
  elsif p_tipo='conclusao' and t.status='em_execucao' then v_tipo:='solicitacao_conclusao'; v_status:='aguardando_validacao';
  elsif p_tipo='impedimento' and t.status in ('nao_iniciada','em_execucao','pausada') then v_tipo:='impedimento'; v_status:='bloqueada';
  else raise exception 'Esta acao nao e permitida no estado atual da tarefa.'; end if;
  if p_tipo='impedimento' and coalesce(p_motivo,'') not in ('falta_material','falta_ferramenta','frente_ocupada','projeto_pendente','chuva','espera_equipe','seguranca','outro') then raise exception 'Informe um motivo valido.'; end if;
  if p_tipo in ('inicio','retomada') and p_quantidade<>0 then raise exception 'Quantidade nao permitida nesta acao.'; end if;
  insert into public.evolucoes_tarefa(tarefa_id,colaborador_id,tipo,quantidade_realizada,motivo_impedimento,observacao)
  values(p_tarefa,c.colaborador_id,v_tipo,p_quantidade,case when p_tipo='impedimento' then p_motivo end,p_observacao)
  returning id into v_evento;
  update public.tarefas set status=v_status,atualizado_em=now() where id=p_tarefa;
  insert into public.sessoes_operario(canal_id,tarefa_ativa_id,estado,atualizado_em)
  values(p_canal,case when v_status='em_execucao' then p_tarefa else null end,'menu',now())
  on conflict (canal_id) do update set
    tarefa_ativa_id=excluded.tarefa_ativa_id,estado='menu',atualizado_em=now();
  return jsonb_build_object('evento_id',v_evento,'status',v_status,'tarefa_id',p_tarefa);
end $$;

create function public.obter_sessao_whatsapp(p_canal bigint) returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'canal_id',c.id,'obra_id',c.obra_id,'colaborador_id',c.colaborador_id,
    'status',c.status,'tarefa_ativa_id',s.tarefa_ativa_id
  ) from public.canais_operario c
  left join public.sessoes_operario s on s.canal_id=c.id
  where c.id=p_canal and c.tipo='whatsapp';
$$;

create function public.registrar_evidencia_whatsapp(
  p_canal bigint,p_tarefa integer,p_provider_id text,p_storage_path text,
  p_mime_type text,p_legenda text default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare c public.canais_operario; v_id bigint;
begin
  if not private.tarefa_atribuida(p_canal,p_tarefa) then raise exception 'Tarefa nao atribuida a este colaborador.'; end if;
  select * into c from public.canais_operario where id=p_canal and status='ativo';
  if p_storage_path !~ ('^'||c.obra_id::text||'/'||p_tarefa::text||'/') then raise exception 'Caminho de arquivo invalido.'; end if;
  insert into public.evidencias_tarefa(tarefa_id,colaborador_id,canal_id,inbox_provider_id,storage_path,mime_type,legenda)
  values(p_tarefa,c.colaborador_id,p_canal,p_provider_id,p_storage_path,p_mime_type,p_legenda)
  returning id into v_id;
  return v_id;
end $$;

create function public.finalizar_whatsapp_inbox(p_provider_id text,p_status text,p_erro text default null) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if p_status not in ('processado','ignorado','erro') then raise exception 'Status invalido.'; end if;
  update public.whatsapp_inbox set status=p_status,erro=p_erro,processado_em=now()
  where provider_id=p_provider_id;
end $$;

create function public.claim_whatsapp_outbox(p_limite integer default 20)
returns table(id bigint,canal_id bigint,telefone_e164 text,tipo text,corpo text,metadados jsonb)
language plpgsql security definer set search_path = '' as $$
begin
  update public.whatsapp_outbox set status='pendente',processando_em=null
  where status='processando' and processando_em < now()-interval '5 minutes';
  return query
  with fila as (
    select o.id from public.whatsapp_outbox o
    where o.status='pendente' and o.disponivel_em<=now() and o.tentativas<5
    order by o.id for update skip locked limit greatest(1,least(p_limite,100))
  ), atualizada as (
    update public.whatsapp_outbox o set status='processando',processando_em=now(),tentativas=tentativas+1
    from fila where o.id=fila.id
    returning o.id,o.canal_id,o.telefone_e164,o.tipo,o.corpo,o.metadados
  ) select * from atualizada;
end $$;

create function public.finalizar_whatsapp_outbox(
  p_id bigint,p_enviado boolean,p_provider_id text default null,p_erro text default null
) returns void
language plpgsql security definer set search_path = '' as $$
begin
  update public.whatsapp_outbox set
    status=case when p_enviado then 'enviado' when tentativas>=5 then 'erro' else 'pendente' end,
    enviado_em=case when p_enviado then now() else enviado_em end,
    provider_id=case when p_enviado then p_provider_id else provider_id end,
    ultimo_erro=case when p_enviado then null else left(p_erro,1000) end,
    disponivel_em=case when p_enviado then disponivel_em else now() + (interval '30 seconds' * greatest(tentativas,1)) end,
    processando_em=null
  where id=p_id and status='processando';
end $$;

create function private.enfileirar_tarefa_whatsapp() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.whatsapp_outbox(canal_id,telefone_e164,corpo,metadados)
  select distinct c.id,c.telefone_e164,
    format(
      'Nova tarefa #%s\nData: %s%s\nServico: %s\nFrente: %s\nMeta: %s %s\n\nResponda *MENU* para ver os comandos.',
      new.id,to_char(new.data,'DD/MM/YYYY'),
      case when new.turno is null then '' else ' · '||new.turno end,
      sv.nome,f.nome,new.quantidade_meta,new.unidade
    ),
    jsonb_build_object('tarefa_id',new.id,'evento','nova_tarefa')
  from public.canais_operario c
  join public.servicos sv on sv.id=new.servico_id
  join public.frentes f on f.id=new.frente_id
  where c.obra_id=new.obra_id and c.tipo='whatsapp' and c.status='ativo'
    and (
      c.colaborador_id=new.colaborador_id
      or exists (
        select 1 from public.equipe_colaboradores ec
        where ec.equipe_id=new.equipe_id and ec.colaborador_id=c.colaborador_id
          and ec.ativo and new.data>=ec.data_inicio
          and (ec.data_fim is null or new.data<=ec.data_fim)
      )
    );
  return new;
end $$;

create trigger enfileirar_tarefa_whatsapp
after insert on public.tarefas for each row
execute function private.enfileirar_tarefa_whatsapp();

revoke all on function private.normalizar_telefone(text) from public,anon,authenticated;
revoke all on function private.tarefa_atribuida(bigint,integer) from public,anon,authenticated;
revoke all on function private.enfileirar_tarefa_whatsapp() from public,anon,authenticated;
revoke all on function public.registrar_whatsapp_inbox(text,text,text,text,boolean,jsonb) from public,anon,authenticated;
revoke all on function public.ativar_canal_whatsapp(text,text) from public,anon,authenticated;
revoke all on function public.listar_tarefas_whatsapp(bigint) from public,anon,authenticated;
revoke all on function public.registrar_evolucao_operario(bigint,integer,text,numeric,text,text) from public,anon,authenticated;
revoke all on function public.obter_sessao_whatsapp(bigint) from public,anon,authenticated;
revoke all on function public.registrar_evidencia_whatsapp(bigint,integer,text,text,text,text) from public,anon,authenticated;
revoke all on function public.finalizar_whatsapp_inbox(text,text,text) from public,anon,authenticated;
revoke all on function public.claim_whatsapp_outbox(integer) from public,anon,authenticated;
revoke all on function public.finalizar_whatsapp_outbox(bigint,boolean,text,text) from public,anon,authenticated;

grant execute on function public.registrar_whatsapp_inbox(text,text,text,text,boolean,jsonb) to service_role;
grant execute on function public.ativar_canal_whatsapp(text,text) to service_role;
grant execute on function public.listar_tarefas_whatsapp(bigint) to service_role;
grant execute on function public.registrar_evolucao_operario(bigint,integer,text,numeric,text,text) to service_role;
grant execute on function public.obter_sessao_whatsapp(bigint) to service_role;
grant execute on function public.registrar_evidencia_whatsapp(bigint,integer,text,text,text,text) to service_role;
grant execute on function public.finalizar_whatsapp_inbox(text,text,text) to service_role;
grant execute on function public.claim_whatsapp_outbox(integer) to service_role;
grant execute on function public.finalizar_whatsapp_outbox(bigint,boolean,text,text) to service_role;
grant select,insert,update on public.canais_operario,public.sessoes_operario,
  public.whatsapp_outbox,public.whatsapp_inbox,public.evidencias_tarefa to service_role;
grant usage,select on all sequences in schema public to service_role;
